//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data8.MvcValidation.TelFormattingWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.data-8.co.uk/integr8", ConfigurationName="TelFormattingWS.TelephoneFormattingSoap")]
    public interface TelephoneFormattingSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.data-8.co.uk/integr8/FormatTelephoneNumberSimple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Data8.MvcValidation.TelFormattingWS.TelephoneFormattingOutput FormatTelephoneNumberSimple(string username, string password, string number);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.data-8.co.uk/integr8/FormatTelephoneNumberMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Data8.MvcValidation.TelFormattingWS.TelephoneFormattingOutput[] FormatTelephoneNumberMultiple(string username, string password, string[] requests, Data8.MvcValidation.TelFormattingWS.Option[] options);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.data-8.co.uk/integr8/FormatTelephoneNumber", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Data8.MvcValidation.TelFormattingWS.TelephoneFormattingOutput FormatTelephoneNumber(string username, string password, string number, Data8.MvcValidation.TelFormattingWS.Option[] options);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.data-8.co.uk/integr8")]
    public partial class TelephoneFormattingOutput : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Status statusField;
        
        private string formattedNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Status Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string FormattedNumber {
            get {
                return this.formattedNumberField;
            }
            set {
                this.formattedNumberField = value;
                this.RaisePropertyChanged("FormattedNumber");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.data-8.co.uk/integr8")]
    public partial class Status : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool successField;
        
        private string errorMessageField;
        
        private float creditsRemainingField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
                this.RaisePropertyChanged("Success");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
                this.RaisePropertyChanged("ErrorMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public float CreditsRemaining {
            get {
                return this.creditsRemainingField;
            }
            set {
                this.creditsRemainingField = value;
                this.RaisePropertyChanged("CreditsRemaining");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.data-8.co.uk/integr8")]
    public partial class Option : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TelephoneFormattingSoapChannel : Data8.MvcValidation.TelFormattingWS.TelephoneFormattingSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TelephoneFormattingSoapClient : System.ServiceModel.ClientBase<Data8.MvcValidation.TelFormattingWS.TelephoneFormattingSoap>, Data8.MvcValidation.TelFormattingWS.TelephoneFormattingSoap {
        
        public TelephoneFormattingSoapClient() {
        }
        
        public TelephoneFormattingSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TelephoneFormattingSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TelephoneFormattingSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TelephoneFormattingSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Data8.MvcValidation.TelFormattingWS.TelephoneFormattingOutput FormatTelephoneNumberSimple(string username, string password, string number) {
            return base.Channel.FormatTelephoneNumberSimple(username, password, number);
        }
        
        public Data8.MvcValidation.TelFormattingWS.TelephoneFormattingOutput[] FormatTelephoneNumberMultiple(string username, string password, string[] requests, Data8.MvcValidation.TelFormattingWS.Option[] options) {
            return base.Channel.FormatTelephoneNumberMultiple(username, password, requests, options);
        }
        
        public Data8.MvcValidation.TelFormattingWS.TelephoneFormattingOutput FormatTelephoneNumber(string username, string password, string number, Data8.MvcValidation.TelFormattingWS.Option[] options) {
            return base.Channel.FormatTelephoneNumber(username, password, number, options);
        }
    }
}
