//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Data8.MvcValidation.TelFormattingWS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="TelephoneFormattingSoap", Namespace="http://www.data-8.co.uk/integr8")]
    public partial class TelephoneFormatting : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback FormatTelephoneNumberSimpleOperationCompleted;
        
        private System.Threading.SendOrPostCallback FormatTelephoneNumberMultipleOperationCompleted;
        
        private System.Threading.SendOrPostCallback FormatTelephoneNumberOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public TelephoneFormatting() {
            this.Url = global::Data8.MvcValidation.Properties.Settings.Default.Data8_MvcValidation_TelFormattingWS_TelephoneFormatting;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event FormatTelephoneNumberSimpleCompletedEventHandler FormatTelephoneNumberSimpleCompleted;
        
        /// <remarks/>
        public event FormatTelephoneNumberMultipleCompletedEventHandler FormatTelephoneNumberMultipleCompleted;
        
        /// <remarks/>
        public event FormatTelephoneNumberCompletedEventHandler FormatTelephoneNumberCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.data-8.co.uk/integr8/FormatTelephoneNumberSimple", RequestNamespace="http://www.data-8.co.uk/integr8", ResponseNamespace="http://www.data-8.co.uk/integr8", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TelephoneFormattingOutput FormatTelephoneNumberSimple(string username, string password, string number) {
            object[] results = this.Invoke("FormatTelephoneNumberSimple", new object[] {
                        username,
                        password,
                        number});
            return ((TelephoneFormattingOutput)(results[0]));
        }
        
        /// <remarks/>
        public void FormatTelephoneNumberSimpleAsync(string username, string password, string number) {
            this.FormatTelephoneNumberSimpleAsync(username, password, number, null);
        }
        
        /// <remarks/>
        public void FormatTelephoneNumberSimpleAsync(string username, string password, string number, object userState) {
            if ((this.FormatTelephoneNumberSimpleOperationCompleted == null)) {
                this.FormatTelephoneNumberSimpleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFormatTelephoneNumberSimpleOperationCompleted);
            }
            this.InvokeAsync("FormatTelephoneNumberSimple", new object[] {
                        username,
                        password,
                        number}, this.FormatTelephoneNumberSimpleOperationCompleted, userState);
        }
        
        private void OnFormatTelephoneNumberSimpleOperationCompleted(object arg) {
            if ((this.FormatTelephoneNumberSimpleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FormatTelephoneNumberSimpleCompleted(this, new FormatTelephoneNumberSimpleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.data-8.co.uk/integr8/FormatTelephoneNumberMultiple", RequestNamespace="http://www.data-8.co.uk/integr8", ResponseNamespace="http://www.data-8.co.uk/integr8", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TelephoneFormattingOutput[] FormatTelephoneNumberMultiple(string username, string password, string[] requests, Option[] options) {
            object[] results = this.Invoke("FormatTelephoneNumberMultiple", new object[] {
                        username,
                        password,
                        requests,
                        options});
            return ((TelephoneFormattingOutput[])(results[0]));
        }
        
        /// <remarks/>
        public void FormatTelephoneNumberMultipleAsync(string username, string password, string[] requests, Option[] options) {
            this.FormatTelephoneNumberMultipleAsync(username, password, requests, options, null);
        }
        
        /// <remarks/>
        public void FormatTelephoneNumberMultipleAsync(string username, string password, string[] requests, Option[] options, object userState) {
            if ((this.FormatTelephoneNumberMultipleOperationCompleted == null)) {
                this.FormatTelephoneNumberMultipleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFormatTelephoneNumberMultipleOperationCompleted);
            }
            this.InvokeAsync("FormatTelephoneNumberMultiple", new object[] {
                        username,
                        password,
                        requests,
                        options}, this.FormatTelephoneNumberMultipleOperationCompleted, userState);
        }
        
        private void OnFormatTelephoneNumberMultipleOperationCompleted(object arg) {
            if ((this.FormatTelephoneNumberMultipleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FormatTelephoneNumberMultipleCompleted(this, new FormatTelephoneNumberMultipleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.data-8.co.uk/integr8/FormatTelephoneNumber", RequestNamespace="http://www.data-8.co.uk/integr8", ResponseNamespace="http://www.data-8.co.uk/integr8", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TelephoneFormattingOutput FormatTelephoneNumber(string username, string password, string number, Option[] options) {
            object[] results = this.Invoke("FormatTelephoneNumber", new object[] {
                        username,
                        password,
                        number,
                        options});
            return ((TelephoneFormattingOutput)(results[0]));
        }
        
        /// <remarks/>
        public void FormatTelephoneNumberAsync(string username, string password, string number, Option[] options) {
            this.FormatTelephoneNumberAsync(username, password, number, options, null);
        }
        
        /// <remarks/>
        public void FormatTelephoneNumberAsync(string username, string password, string number, Option[] options, object userState) {
            if ((this.FormatTelephoneNumberOperationCompleted == null)) {
                this.FormatTelephoneNumberOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFormatTelephoneNumberOperationCompleted);
            }
            this.InvokeAsync("FormatTelephoneNumber", new object[] {
                        username,
                        password,
                        number,
                        options}, this.FormatTelephoneNumberOperationCompleted, userState);
        }
        
        private void OnFormatTelephoneNumberOperationCompleted(object arg) {
            if ((this.FormatTelephoneNumberCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FormatTelephoneNumberCompleted(this, new FormatTelephoneNumberCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.data-8.co.uk/integr8")]
    public partial class TelephoneFormattingOutput {
        
        private Status statusField;
        
        private string formattedNumberField;
        
        /// <remarks/>
        public Status Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string FormattedNumber {
            get {
                return this.formattedNumberField;
            }
            set {
                this.formattedNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.data-8.co.uk/integr8")]
    public partial class Status {
        
        private bool successField;
        
        private string errorMessageField;
        
        private float creditsRemainingField;
        
        /// <remarks/>
        public bool Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
        
        /// <remarks/>
        public float CreditsRemaining {
            get {
                return this.creditsRemainingField;
            }
            set {
                this.creditsRemainingField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.data-8.co.uk/integr8")]
    public partial class Option {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void FormatTelephoneNumberSimpleCompletedEventHandler(object sender, FormatTelephoneNumberSimpleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FormatTelephoneNumberSimpleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FormatTelephoneNumberSimpleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TelephoneFormattingOutput Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TelephoneFormattingOutput)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void FormatTelephoneNumberMultipleCompletedEventHandler(object sender, FormatTelephoneNumberMultipleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FormatTelephoneNumberMultipleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FormatTelephoneNumberMultipleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TelephoneFormattingOutput[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TelephoneFormattingOutput[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void FormatTelephoneNumberCompletedEventHandler(object sender, FormatTelephoneNumberCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FormatTelephoneNumberCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FormatTelephoneNumberCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TelephoneFormattingOutput Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TelephoneFormattingOutput)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591