//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data8.MvcValidation.EmailValidationWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.data-8.co.uk/integr8", ConfigurationName="EmailValidationWS.EmailValidationSoap")]
    public interface EmailValidationSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.data-8.co.uk/integr8/IsValidSimple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(InputRecord))]
        Data8.MvcValidation.EmailValidationWS.EmailValidationOutput IsValidSimple(string username, string password, string email, Data8.MvcValidation.EmailValidationWS.EmailValidationLevel level);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.data-8.co.uk/integr8/IsValid", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(InputRecord))]
        Data8.MvcValidation.EmailValidationWS.EmailValidationOutput IsValid(string username, string password, string email, Data8.MvcValidation.EmailValidationWS.EmailValidationLevel level, Data8.MvcValidation.EmailValidationWS.Option[] options);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.data-8.co.uk/integr8/IsValidMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(InputRecord))]
        Data8.MvcValidation.EmailValidationWS.EmailValidationOutput[] IsValidMultiple(string username, string password, Data8.MvcValidation.EmailValidationWS.EmailValidationRequest[] requests, Data8.MvcValidation.EmailValidationWS.Option[] options);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.data-8.co.uk/integr8/CleanseSimple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(InputRecord))]
        Data8.MvcValidation.EmailValidationWS.EmailCleanseOutput CleanseSimple(string username, string password, string email, Data8.MvcValidation.EmailValidationWS.EmailValidationLevel level, string title, string forename, string middleName, string surname, string company, string address);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.data-8.co.uk/integr8/Cleanse", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(InputRecord))]
        Data8.MvcValidation.EmailValidationWS.EmailCleanseOutput Cleanse(string username, string password, string email, Data8.MvcValidation.EmailValidationWS.EmailValidationLevel level, Data8.MvcValidation.EmailValidationWS.BusinessInputRecord record, Data8.MvcValidation.EmailValidationWS.Option[] options);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.data-8.co.uk/integr8/CleanseMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(InputRecord))]
        Data8.MvcValidation.EmailValidationWS.EmailCleanseOutput[] CleanseMultiple(string username, string password, Data8.MvcValidation.EmailValidationWS.EmailCleanseRequest[] requests, Data8.MvcValidation.EmailValidationWS.Option[] options);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.data-8.co.uk/integr8/CodeVerifySimple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(InputRecord))]
        Data8.MvcValidation.EmailValidationWS.EmailCodeVerificationOutput CodeVerifySimple(string username, string password, string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.data-8.co.uk/integr8/CodeVerify", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(InputRecord))]
        Data8.MvcValidation.EmailValidationWS.EmailCodeVerificationOutput CodeVerify(string username, string password, string email, Data8.MvcValidation.EmailValidationWS.Option[] options);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.data-8.co.uk/integr8")]
    public enum EmailValidationLevel {
        
        /// <remarks/>
        Syntax,
        
        /// <remarks/>
        MX,
        
        /// <remarks/>
        Server,
        
        /// <remarks/>
        Address,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.data-8.co.uk/integr8")]
    public partial class EmailValidationOutput : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Status statusField;
        
        private EmailValidationResult resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Status Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public EmailValidationResult Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("Result");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.data-8.co.uk/integr8")]
    public partial class Status : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool successField;
        
        private string errorMessageField;
        
        private float creditsRemainingField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
                this.RaisePropertyChanged("Success");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
                this.RaisePropertyChanged("ErrorMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public float CreditsRemaining {
            get {
                return this.creditsRemainingField;
            }
            set {
                this.creditsRemainingField = value;
                this.RaisePropertyChanged("CreditsRemaining");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.data-8.co.uk/integr8")]
    public partial class EmailCodeVerificationOutput : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Status statusField;
        
        private EmailValidationResult resultField;
        
        private string codeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Status Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public EmailValidationResult Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("Result");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.data-8.co.uk/integr8")]
    public enum EmailValidationResult {
        
        /// <remarks/>
        Blank,
        
        /// <remarks/>
        Invalid,
        
        /// <remarks/>
        Inconclusive,
        
        /// <remarks/>
        GreyListed,
        
        /// <remarks/>
        CatchAll,
        
        /// <remarks/>
        Valid,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.data-8.co.uk/integr8")]
    public partial class EmailCleanseRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string emailField;
        
        private EmailValidationLevel levelField;
        
        private BusinessInputRecord recordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("Email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public EmailValidationLevel Level {
            get {
                return this.levelField;
            }
            set {
                this.levelField = value;
                this.RaisePropertyChanged("Level");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public BusinessInputRecord Record {
            get {
                return this.recordField;
            }
            set {
                this.recordField = value;
                this.RaisePropertyChanged("Record");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.data-8.co.uk/integr8")]
    public partial class BusinessInputRecord : InputRecord {
        
        private string companyNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string CompanyName {
            get {
                return this.companyNameField;
            }
            set {
                this.companyNameField = value;
                this.RaisePropertyChanged("CompanyName");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BusinessInputRecord))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.data-8.co.uk/integr8")]
    public partial class InputRecord : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Name nameField;
        
        private Address addressField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Name Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Address Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
                this.RaisePropertyChanged("Address");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.data-8.co.uk/integr8")]
    public partial class Name : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string titleField;
        
        private string forenameField;
        
        private string middleNameField;
        
        private string surnameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("Title");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Forename {
            get {
                return this.forenameField;
            }
            set {
                this.forenameField = value;
                this.RaisePropertyChanged("Forename");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string MiddleName {
            get {
                return this.middleNameField;
            }
            set {
                this.middleNameField = value;
                this.RaisePropertyChanged("MiddleName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Surname {
            get {
                return this.surnameField;
            }
            set {
                this.surnameField = value;
                this.RaisePropertyChanged("Surname");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.data-8.co.uk/integr8")]
    public partial class Address : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string[] linesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public string[] Lines {
            get {
                return this.linesField;
            }
            set {
                this.linesField = value;
                this.RaisePropertyChanged("Lines");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.data-8.co.uk/integr8")]
    public partial class EmailCleanseOutput : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Status statusField;
        
        private EmailValidationResult resultField;
        
        private bool originalValidField;
        
        private EmailTypeResult emailTypeField;
        
        private string suggestedEmailAddressField;
        
        private string commentField;
        
        private string salutationField;
        
        private string structureUsedField;
        
        private Name parsedNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Status Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public EmailValidationResult Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("Result");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool OriginalValid {
            get {
                return this.originalValidField;
            }
            set {
                this.originalValidField = value;
                this.RaisePropertyChanged("OriginalValid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public EmailTypeResult EmailType {
            get {
                return this.emailTypeField;
            }
            set {
                this.emailTypeField = value;
                this.RaisePropertyChanged("EmailType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string SuggestedEmailAddress {
            get {
                return this.suggestedEmailAddressField;
            }
            set {
                this.suggestedEmailAddressField = value;
                this.RaisePropertyChanged("SuggestedEmailAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Comment {
            get {
                return this.commentField;
            }
            set {
                this.commentField = value;
                this.RaisePropertyChanged("Comment");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Salutation {
            get {
                return this.salutationField;
            }
            set {
                this.salutationField = value;
                this.RaisePropertyChanged("Salutation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string StructureUsed {
            get {
                return this.structureUsedField;
            }
            set {
                this.structureUsedField = value;
                this.RaisePropertyChanged("StructureUsed");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public Name ParsedName {
            get {
                return this.parsedNameField;
            }
            set {
                this.parsedNameField = value;
                this.RaisePropertyChanged("ParsedName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.data-8.co.uk/integr8")]
    public enum EmailTypeResult {
        
        /// <remarks/>
        Personal,
        
        /// <remarks/>
        ISP,
        
        /// <remarks/>
        Free,
        
        /// <remarks/>
        Generic,
        
        /// <remarks/>
        Disposable,
        
        /// <remarks/>
        Blank,
        
        /// <remarks/>
        SpamTrap,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.data-8.co.uk/integr8")]
    public partial class EmailValidationRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string emailField;
        
        private EmailValidationLevel levelField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("Email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public EmailValidationLevel Level {
            get {
                return this.levelField;
            }
            set {
                this.levelField = value;
                this.RaisePropertyChanged("Level");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.data-8.co.uk/integr8")]
    public partial class Option : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EmailValidationSoapChannel : Data8.MvcValidation.EmailValidationWS.EmailValidationSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EmailValidationSoapClient : System.ServiceModel.ClientBase<Data8.MvcValidation.EmailValidationWS.EmailValidationSoap>, Data8.MvcValidation.EmailValidationWS.EmailValidationSoap {
        
        public EmailValidationSoapClient() {
        }
        
        public EmailValidationSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EmailValidationSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmailValidationSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmailValidationSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Data8.MvcValidation.EmailValidationWS.EmailValidationOutput IsValidSimple(string username, string password, string email, Data8.MvcValidation.EmailValidationWS.EmailValidationLevel level) {
            return base.Channel.IsValidSimple(username, password, email, level);
        }
        
        public Data8.MvcValidation.EmailValidationWS.EmailValidationOutput IsValid(string username, string password, string email, Data8.MvcValidation.EmailValidationWS.EmailValidationLevel level, Data8.MvcValidation.EmailValidationWS.Option[] options) {
            return base.Channel.IsValid(username, password, email, level, options);
        }
        
        public Data8.MvcValidation.EmailValidationWS.EmailValidationOutput[] IsValidMultiple(string username, string password, Data8.MvcValidation.EmailValidationWS.EmailValidationRequest[] requests, Data8.MvcValidation.EmailValidationWS.Option[] options) {
            return base.Channel.IsValidMultiple(username, password, requests, options);
        }
        
        public Data8.MvcValidation.EmailValidationWS.EmailCleanseOutput CleanseSimple(string username, string password, string email, Data8.MvcValidation.EmailValidationWS.EmailValidationLevel level, string title, string forename, string middleName, string surname, string company, string address) {
            return base.Channel.CleanseSimple(username, password, email, level, title, forename, middleName, surname, company, address);
        }
        
        public Data8.MvcValidation.EmailValidationWS.EmailCleanseOutput Cleanse(string username, string password, string email, Data8.MvcValidation.EmailValidationWS.EmailValidationLevel level, Data8.MvcValidation.EmailValidationWS.BusinessInputRecord record, Data8.MvcValidation.EmailValidationWS.Option[] options) {
            return base.Channel.Cleanse(username, password, email, level, record, options);
        }
        
        public Data8.MvcValidation.EmailValidationWS.EmailCleanseOutput[] CleanseMultiple(string username, string password, Data8.MvcValidation.EmailValidationWS.EmailCleanseRequest[] requests, Data8.MvcValidation.EmailValidationWS.Option[] options) {
            return base.Channel.CleanseMultiple(username, password, requests, options);
        }
        
        public Data8.MvcValidation.EmailValidationWS.EmailCodeVerificationOutput CodeVerifySimple(string username, string password, string email) {
            return base.Channel.CodeVerifySimple(username, password, email);
        }
        
        public Data8.MvcValidation.EmailValidationWS.EmailCodeVerificationOutput CodeVerify(string username, string password, string email, Data8.MvcValidation.EmailValidationWS.Option[] options) {
            return base.Channel.CodeVerify(username, password, email, options);
        }
    }
}
